drop table ticket if exists;
drop table ticket_user if exists;
drop table user if exists;
create table ticket (id bigint generated by default as identity, created_at TIMESTAMP, description varchar(255), title varchar(255), primary key (id));
create table ticket_user (user_id bigint not null, ticket_id bigint not null, primary key (user_id, ticket_id));
create table user (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role varchar(255), username varchar(255) not null, primary key (id));
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table ticket_user add constraint FK15wwc2ukb5w7qs8mw6hvxi8ep foreign key (ticket_id) references ticket;
alter table ticket_user add constraint FKnmy1mk4o43f7y6a3lodg7n7o9 foreign key (user_id) references user;